import type { Metadata } from "next";
import { Platypi } from "next/font/google";
import "./globals.css";
import Provider from "@/provider";
import { Toaster } from "react-hot-toast";
import TopLoader from "@/components/toploader";

const platypi = Platypi({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${platypi.className} custom-scroll-horizontal`}>
        <TopLoader />
        <Provider>{children}</Provider>
        <Toaster position="bottom-center" reverseOrder />
      </body>
    </html>
  );
}
